spring:
  application:
    name: "@project.artifactId@"

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

server:
  port: 8080

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  metrics:
    export:
      jmx:
        domain: metrics
        enabled: true
